include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_relative_imports
    - unawaited_futures
    - always_declare_return_types
    - avoid_unused_constructor_parameters
